profiles:
  SingleExternalMonitor:
    name: "External monitor"
    when:
      connected: "$only(eDP1, HDMI1)"
    then:
      - configure-displays:
          "*":
            state: "off"
          HDMI1:
            mode: '$preferredResolution'
  InternalDisplayOnly:
    when:
      connected: "$only(eDP1)"
    then:
      - configure-displays:
          "*":
            state: "off"
          eDP1:
            mode: "$preferredResolution"
            position: '0x0'
            primary: true
  2Monitors:
    when:
      connected: "HDMI1, HDMI2"
    then:
      - configure-displays:
          "*":
            state: "off"
          HDMI1:
            mode: "$preferredResolution"
            position: '0x0'
            primary: true
          HDMI2:
            mode: "$preferredResolution"
            position: 'right-of HDMI1'
            primary: true
actions:
  setupInternalDisplayOnly:
    - execute-xrandr: '--auto'