profiles:
  SingleExternalMonitor:
    when:
      connected-only: "eDP1, HDMI1"
    then:
      - configure-displays:
          "*":
            state: "off"
          HDMI1:
            mode: '$preferredResolution'
  InternalDisplayOnly:
    when:
      connected-only: "eDP1"
    then:
      - configure-displays:
          "*":
            state: "off"
          eDP1:
            auto: true
  2Monitors:
    when:
      connected: "eDP1, HDMI1, HDMI2"
    then:
      - configure-displays:
          "*":
            state: "off"
          HDMI1:
            mode: "1920x1080"
            position: '0x0'
            primary: true
          HDMI2:
            mode: "1920x1080"
            position: 'right-of HDMI1'
            primary: true
actions:
  setupInternalDisplayOnly:
    - execute-xrandr: '--auto'