profiles:
  SingleExternalMonitor:
    # Conditions section should support expressions as well as executrors
    # Whole configuration object should be available as context
    when:
      connected-displays: "$only(eDP1, HDMI1)" # This expression defines matching strategy!
      connected-displays: "$oneof(eDP1, HDMI1)"
    then:
      - set-variable: "varName  = 4"
      - set-variable: "varName1 = $varName"    # expression calculation logic should be supported everywhere
      - configure-displays:
          "*":
            state: "off"
          HDMI1:
            primary: true
            mode: "1920x1080"
            position: "left-of eDP1"
            rotate: "normal"
  InternalDisplayOnly:
    when:
      connected-only: "eDP1"
    then:
      - xrandr: '--output HDMI2 --off --output HDMI1 --off --output DP1 --off --output VIRTUAL1 --off --output eDP1 --auto'
  2Monitors:
    when:
      connected: "eDP1, HDMI1, HDMI2"
    then:
      - xrandr: '--output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output eDP1 --off --output VIRTUAL1 --off'

  # ------------------------
  # PULSEAUDIO CONFIGURATION
  # ------------------------
  WirelessHeadsetConnected:
    when:
      - pulseaudio-available: 'H600*'
    then:
      - configure-pulseaudio:
        '$findPulseAudioOutput(H600)':
          default: True
  WirelessHeadsetDisconnected:
    when:
      - pulseaudio-available: '$not(H600*)'
    then:
      - configure-pulseaudio:
        '$findPulseAudioOutput(Built-in)':
          default: True
          port: $findPulseAudioPort(Headset)
actions:
  setupInternalDisplayOnly:
    - execute-xrandr: '--auto'